### ISSUE TITLE
Refactor player character and enemies into separate class files to be more OOP.

### ISSUE THREAD

**Issue by TelefunkenU87** [Fizban-Wisefire/ConsoleAdventure#1]
Right now, all character/player/item classes are in the same file as the main game program.

We want each class in their own file.
- `Character.cs`
- `Player.cs`
- `Item.cs`

Acceptance Criteria:
- Create a new branch for doing this work.
- When ready, create a pull request into main for review.
- Code for classes should be in their own files.
- Original game code should still work after code is moved to their own class files.
- Original class code is removed from `Program.cs`

**Comment by Fizban-Wisefire** [comment]
Complete in SeperateClasses branch and merged on 3-1-24.
